# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'plugin.json'
        prop_path: 'Version'  
    - name: Restore dependencies
      run: dotnet Flow.Launcher.Plugin.Bitwarden.csproj restore
    - name: Build
      run: dotnet build Flow.Launcher.Plugin.Bitwarden.csproj --no-restore
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "Flow.Launcher.Plugin.BitwardenSearch*"
        tag_name: "v${{steps.version.outputs.prop}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
