# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'plugin.json'
        prop_path: 'Version'  
    - name: Publish package
      run: dotnet publish Flow.Launcher.Plugin.Bitwarden.csproj -c Release -r win-x64 --no-self-contained -o publish/
    - uses: actions/upload-artifact@v4
      with:
          name: Bitwarden
          path: publish/
          if-no-files-found: error
